### ISSUE TITLE
Question about the dependency named `plaid`.

### ISSUE THREAD

**Issue by limzh00** [amyxlu/cheap-proteins#3]
Greetings. Thanks for you excellent work. When trying to run through your pipeline, I found a library called `plaid` in code. I wonder what it is. It seems an inconsistent dependency.

**Comment by amyxlu** [comment]
Hi, thanks for pointing this out -- some changes were developed & tested in an environment for a follow-up project, and I've pushed some relevant changes to those dependencies. Closing this issue, feel free to open a new one as needed!

**Comment by limzh00** [comment]
![20241011-172128](https://github.com/user-attachments/assets/b1cadf38-cc8b-44ec-9305-42542e6d927f)
Also, your checkpoints depend on `plaid`. It would be nice if you push a new one.

**Comment by amyxlu** [comment]
That should've been fixed in the last update -- could you try again and if it doesn't work, can you post the code to reproduce the error?

For context on the error, we'd trained the models using PyTorch Lightning, which pickles the inputs used to instantiate the model. In the pre-release code used during training, the latent scaler class (part of the external `plaid` package) was passed as an input to the model `__init__` function, hence why it's unable to be unpickled here. The checkpoints should be modified now.

**Comment by limzh00** [comment]
It has been fixed, thanks.
