### ISSUE TITLE
How do you reconstruct the structure from the embeddings (Figure 5)

### ISSUE THREAD

**Issue by jakublala** [amyxlu/cheap-proteins#7]
![image](https://github.com/user-attachments/assets/dcc55784-851d-4192-bc60-548536692978)

**Comment by jakublala** [comment]
In the paper, you don't mention what is this structure that you depict (e.g. its UniProt ID), or you mention exactly how you get the structure from an embedding. Do you do some additional training of some module?

**Comment by patjiang** [comment]
Hello jaku! I believe, based on the paper, and this figure (linked [here](https://www.biorxiv.org/content/biorxiv/early/2024/11/03/2024.08.06.606920/F1.large.jpg?width=800&height=600&carousel=1))
![image](https://github.com/user-attachments/assets/1514fbed-00c7-488a-8632-095b7ef0f3d3)

CHEAP is used as an embedding space compression algorithm to enrich the expressivity of the pre-existing and pretrained ESMFold. If what I am understanding is correct, CHEAP exists due to the author's observation of strange activation functions within the model, and created as a way to also couple seq/structure representations in a model. In this sense, you can think of CHEAP as a model that is trained to optimize the information captured by embeddings generated by ESMFold

Hope this helps! If I am incorrect at any point, please feel free to correct me as well!

**Comment by jakublala** [comment]
Hey @patjiang, thanks for the message. I went through the Appendix and they actually mention it in one of the comments in the pasted code. Effectively, what they do is that they use the CHEAP decoder to get back into the ESM embedding, which is then compatible with ESMFold and then use the original ESMFold.

Still, this is not apparent from the paper straight away, nor is the experiment with structure reconstruction adequately describe (including, for instance, the exact dataset, or what protein is shown in the figure).
